sudo: false

language: php

matrix:
  include:
    - php: 7.4
      env: ANALYZE=true

install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --dev

script:
  - vendor/bin/phpunit tests/*Tests.php
  - vendor/bin/phpunit --exclude-group integration --coverage-text --coverage-clover coverage.xml